# GitHub Pages Configuration
theme: minima
title: SOLO CORN SKILLS
description: Extensible AI Skill Workflows for Solopreneurs
baseurl: "/solo-corn-skills"
url: "https://zbbsdsb.github.io"
author: ceaserzhao
